import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Header } from "./_components/header";
import Footer from "./_components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Saugos Kursai",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const localization = {
  signIn: {
    start: {
      title: "Sveiki sugrįžę !",
      subtitle: "Prašome prisijungti",
      actionText: "Neturite paskyros?",
    },
  },
  signUp: {
    start: {
      title: "Susikurkite paskyrą",
      subtitle: "",
      actionText: "Jau turite paskyrą?",
    },
  },
};
export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <Toaster position="top-center" />
          <Header />
          <div className="min-h-screen pt-[70px]">
            <Suspense>
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </Suspense>
          </div>
          <Footer
            companyName="Saugos Kursai"
            year={new Date().getFullYear()}
            contactEmail="saugoskursai@gmail.com"
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
